name: 'Sign File on Windows'

description: 'Sign a file using SSL.com CodeSignTool v2'

inputs:
  filepath:
    description: 'File to be signed'
    required: true
  sslusername:
    description: 'SSL.com account username'
    required: true
  sslpassword:
    description: 'SSL.com account password'
    required: true
  sslsecretpassword:
    description: 'SSL.com account TOTP secret'
    required: true
  sslclientid:
    description: 'SSL.com account Client Id'
    required: true
  istest:
    description: 'When false, runs on SSL.com Production account, otherwise runs against Sandbox'
    required: false
    default: true
runs:
  using: node16
  main: dist/index.js
