name: Black Duck SCA
on:
  push:
    branches: [main, master, develop, stage, release]
  pull_request:
    branches: [main, master, develop, stage, release]
  workflow_dispatch: {}
jobs:
  scan:
    uses: acresecurity/aac-secops/.github/workflows/_blackducksca.yml@5deb4d089807a2b6f4854e9915c56b8ad4198a75
    secrets: inherit
