name: Black Duck SCA
on:
  push:
    branches: [main, master, develop, stage, release]
  pull_request:
    branches: [main, master, develop, stage, release]
  workflow_dispatch: {}
jobs:
  scan:
    uses: acresecurity/aac-secops/.github/workflows/_blackducksca.yml@d320179ffa037de187f24b1a7982ae58b9d0fcf4
    secrets: inherit
